import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative max-w-screen-2xl bg-[#F5F4F8] mx-auto">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
